import type { LevelDefinition } from './types';

const sharedCrates = [
  { id: 'crate-a', center: { x: -3.1, z: -0.7 }, size: { x: 1.2, z: 2.3 }, height: 1.35 },
  { id: 'crate-b', center: { x: 1.4, z: 1.1 }, size: { x: 1.1, z: 3.4 }, height: 1.55 },
  { id: 'crate-c', center: { x: 4.1, z: -1.8 }, size: { x: 1.6, z: 1.1 }, height: 1.1 },
] as const;

export const levels: readonly LevelDefinition[] = [
  {
    id: 'dock-blackout',
    name: 'Dock Blackout',
    briefing: 'Slip through a half-lit cargo bay and reach the service hatch.',
    parSeconds: 35,
    floorSize: { x: 12, z: 9 },
    start: { x: -5, z: 3.4 },
    goal: { x: 5, z: -3.2 },
    goalRadius: 0.55,
    obstacles: sharedCrates,
    lights: [
      { id: 'lamp-north', position: { x: -2.5, z: -3.2 }, height: 3.4, color: '#6ab7ff', intensity: 95, radius: 5.6 },
      { id: 'lamp-exit', position: { x: 4.6, z: -2.8 }, height: 2.9, color: '#a7ffcb', intensity: 55, radius: 3.2 },
    ],
    enemies: [
      {
        id: 'guard-dock',
        start: { x: -0.2, z: -2.5 },
        patrol: [
          { x: -0.2, z: -2.5 },
          { x: 3.2, z: -2.5 },
          { x: 3.2, z: 2.6 },
          { x: -0.2, z: 2.6 },
        ],
        speed: 1.08,
        visionRange: 3.2,
        visionAngleDegrees: 64,
        pauseSeconds: 0.3,
      },
    ],
    objectives: [
      {
        id: 'dock-keycard',
        type: 'keycard',
        label: 'Gate Keycard',
        position: { x: -1.0, z: -1.2 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'dock-terminal',
        type: 'terminal',
        label: 'Exit Terminal',
        position: { x: 2.4, z: -3.4 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -5, z: 3.4 },
      { x: -4.8, z: -3.8 },
      { x: -1.6, z: -3.8 },
      { x: -1.0, z: -1.2 },
      { x: 2.4, z: -3.4 },
      { x: 5, z: -3.2 },
    ],
  },
  {
    id: 'archive-lanes',
    name: 'Archive Lanes',
    briefing: 'Cross the records room while patrols sweep the narrow aisles.',
    parSeconds: 55,
    floorSize: { x: 14, z: 10 },
    start: { x: -6, z: 4 },
    goal: { x: 6.1, z: -4 },
    goalRadius: 0.55,
    obstacles: [
      { id: 'shelf-a', center: { x: -3.5, z: 0 }, size: { x: 0.9, z: 7.2 }, height: 1.8 },
      { id: 'shelf-b', center: { x: 0.2, z: 0.8 }, size: { x: 0.9, z: 7.2 }, height: 1.8 },
      { id: 'shelf-c', center: { x: 3.8, z: -0.7 }, size: { x: 0.9, z: 7.2 }, height: 1.8 },
      { id: 'desk', center: { x: -5.3, z: -2.6 }, size: { x: 1.7, z: 1.3 }, height: 1.0 },
    ],
    lights: [
      { id: 'lamp-aisle-a', position: { x: -5.3, z: 1.8 }, height: 3.3, color: '#ffd58a', intensity: 62, radius: 4.1 },
      { id: 'lamp-aisle-b', position: { x: 1.9, z: -1.8 }, height: 3.2, color: '#76d7ff', intensity: 72, radius: 4.8 },
      { id: 'lamp-goal', position: { x: 5.9, z: -3.5 }, height: 2.7, color: '#7dff9b', intensity: 48, radius: 3.0 },
    ],
    enemies: [
      {
        id: 'guard-archive-a',
        start: { x: -1.8, z: 3.5 },
        patrol: [
          { x: -1.8, z: 3.5 },
          { x: -1.8, z: -3.5 },
        ],
        speed: 0.95,
        visionRange: 3.3,
        visionAngleDegrees: 58,
        pauseSeconds: 0.45,
      },
      {
        id: 'guard-archive-b',
        start: { x: 2.1, z: -3.7 },
        patrol: [
          { x: 2.1, z: -3.7 },
          { x: 2.1, z: 3.6 },
        ],
        speed: 1.05,
        visionRange: 3.1,
        visionAngleDegrees: 58,
        pauseSeconds: 0.25,
      },
    ],
    objectives: [
      {
        id: 'archive-keycard',
        type: 'keycard',
        label: 'Archive Keycard',
        position: { x: -2.1, z: -4.1 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'archive-terminal',
        type: 'terminal',
        label: 'Records Terminal',
        position: { x: 2.6, z: -4.6 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -6, z: 4 },
      { x: -6.5, z: 4.7 },
      { x: -6.5, z: -3.9 },
      { x: -2.1, z: -4.1 },
      { x: -1.5, z: 4.7 },
      { x: 1.7, z: 4.7 },
      { x: 2.6, z: -4.6 },
      { x: 4.6, z: -4.6 },
      { x: 6.1, z: -4 },
    ],
  },
  {
    id: 'reactor-core',
    name: 'Reactor Core',
    briefing: 'Use cover and timing to cross the reactor floor before lockdown.',
    parSeconds: 60,
    floorSize: { x: 16, z: 11 },
    start: { x: -7, z: 4.4 },
    goal: { x: 7.1, z: -4.4 },
    goalRadius: 0.58,
    obstacles: [
      { id: 'reactor', center: { x: 0, z: 0 }, size: { x: 2.4, z: 2.4 }, height: 2.35 },
      { id: 'console-a', center: { x: -4.7, z: -2.8 }, size: { x: 2.2, z: 1.0 }, height: 1.1 },
      { id: 'console-b', center: { x: 4.7, z: 2.7 }, size: { x: 2.2, z: 1.0 }, height: 1.1 },
      { id: 'pillar-a', center: { x: -2.9, z: 3.1 }, size: { x: 1.1, z: 1.1 }, height: 2.4 },
      { id: 'pillar-b', center: { x: 2.9, z: -3.1 }, size: { x: 1.1, z: 1.1 }, height: 2.4 },
    ],
    lights: [
      { id: 'core-blue', position: { x: 0, z: 0 }, height: 3.1, color: '#57c7ff', intensity: 135, radius: 6.8 },
      { id: 'warning-left', position: { x: -5.6, z: -3.8 }, height: 2.6, color: '#ff5f68', intensity: 52, radius: 3.1 },
      { id: 'warning-right', position: { x: 5.8, z: 3.8 }, height: 2.6, color: '#ffb35f', intensity: 52, radius: 3.1 },
    ],
    enemies: [
      {
        id: 'guard-core-a',
        start: { x: -5.6, z: 0.1 },
        patrol: [
          { x: -5.6, z: 0.1 },
          { x: -1.9, z: -3.6 },
          { x: 1.8, z: -3.6 },
        ],
        speed: 1.15,
        visionRange: 3.6,
        visionAngleDegrees: 62,
        pauseSeconds: 0.2,
      },
      {
        id: 'guard-core-b',
        start: { x: 5.6, z: -0.1 },
        patrol: [
          { x: 5.6, z: -0.1 },
          { x: 1.9, z: 3.6 },
          { x: -1.8, z: 3.6 },
        ],
        speed: 1.12,
        visionRange: 3.6,
        visionAngleDegrees: 62,
        pauseSeconds: 0.2,
      },
    ],
    objectives: [
      {
        id: 'reactor-terminal',
        type: 'terminal',
        label: 'Core Terminal',
        position: { x: -2.5, z: 1.6 },
        radius: 0.68,
        required: true,
      },
      {
        id: 'reactor-keycard',
        type: 'keycard',
        label: 'Reactor Keycard',
        position: { x: 6.7, z: 4.2 },
        radius: 0.62,
        required: true,
      },
    ],
    validationRoute: [
      { x: -7, z: 4.4 },
      { x: -6.8, z: -4.4 },
      { x: -3.2, z: -4.5 },
      { x: -2.5, z: 1.6 },
      { x: 2.3, z: 4.5 },
      { x: 6.7, z: 4.2 },
      { x: 7.1, z: -4.4 },
    ],
  },
  {
    id: 'neon-atrium',
    name: 'Neon Atrium',
    briefing: 'Thread the perimeter of a glass-lit lobby while patrols cross the center.',
    parSeconds: 50,
    floorSize: { x: 18, z: 12 },
    start: { x: -7.2, z: 0.5 },
    goal: { x: 8, z: -5 },
    goalRadius: 0.58,
    obstacles: [
      { id: 'kiosk-west', center: { x: -5.7, z: 1.4 }, size: { x: 1.4, z: 2.2 }, height: 1.25 },
      { id: 'kiosk-east', center: { x: 5.8, z: -1.4 }, size: { x: 1.4, z: 2.2 }, height: 1.25 },
      { id: 'planter-north', center: { x: -1.8, z: -3.2 }, size: { x: 3.6, z: 0.9 }, height: 0.9 },
      { id: 'planter-south', center: { x: 2.0, z: 3.1 }, size: { x: 3.6, z: 0.9 }, height: 0.9 },
      { id: 'glass-a', center: { x: -2.4, z: 0.1 }, size: { x: 0.7, z: 4.2 }, height: 1.9 },
      { id: 'glass-b', center: { x: 2.8, z: -0.1 }, size: { x: 0.7, z: 4.2 }, height: 1.9 },
      { id: 'ticket-desk', center: { x: 0, z: 4.6 }, size: { x: 2.9, z: 0.8 }, height: 1.0 },
    ],
    lights: [
      { id: 'neon-blue', position: { x: -6.5, z: -3.8 }, height: 3.4, color: '#48b8ff', intensity: 82, radius: 5.2 },
      { id: 'neon-magenta', position: { x: 4.9, z: 3.8 }, height: 3.4, color: '#ff58b8', intensity: 76, radius: 5.0 },
      { id: 'atrium-center', position: { x: 0, z: 0 }, height: 4.2, color: '#b7ffef', intensity: 54, radius: 4.6 },
      { id: 'atrium-exit', position: { x: 7.7, z: -4.7 }, height: 2.8, color: '#86ff8a', intensity: 48, radius: 3.2 },
    ],
    enemies: [
      {
        id: 'guard-atrium-cross',
        start: { x: -4.5, z: -1.2 },
        patrol: [
          { x: -4.5, z: -1.2 },
          { x: 4.5, z: -1.2 },
          { x: 4.5, z: 1.2 },
          { x: -4.5, z: 1.2 },
        ],
        speed: 1.22,
        visionRange: 3.7,
        visionAngleDegrees: 60,
        pauseSeconds: 0.18,
      },
      {
        id: 'guard-atrium-ring',
        start: { x: -6.8, z: -4.2 },
        patrol: [
          { x: -6.8, z: -4.2 },
          { x: 6.8, z: -4.2 },
          { x: 6.8, z: 4.2 },
          { x: -6.8, z: 4.2 },
        ],
        speed: 1.0,
        visionRange: 3.4,
        visionAngleDegrees: 56,
        pauseSeconds: 0.25,
      },
    ],
    objectives: [
      {
        id: 'atrium-keycard',
        type: 'keycard',
        label: 'Atrium Keycard',
        position: { x: -3.8, z: -5.2 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'atrium-terminal',
        type: 'terminal',
        label: 'Lobby Terminal',
        position: { x: 3.8, z: -5.2 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -7.2, z: 0.5 },
      { x: -8.3, z: -5.2 },
      { x: -3.8, z: -5.2 },
      { x: 3.8, z: -5.2 },
      { x: 8, z: -5 },
    ],
  },
  {
    id: 'signal-vault',
    name: 'Signal Vault',
    briefing: 'Break through a hardened relay room by weaving between server stacks.',
    parSeconds: 65,
    floorSize: { x: 18, z: 14 },
    start: { x: -8, z: -6 },
    goal: { x: 5.8, z: 4.2 },
    goalRadius: 0.6,
    obstacles: [
      { id: 'rack-a', center: { x: -5.4, z: -1.7 }, size: { x: 1.0, z: 5.0 }, height: 2.05 },
      { id: 'rack-b', center: { x: -2.1, z: 1.7 }, size: { x: 1.0, z: 5.0 }, height: 2.05 },
      { id: 'rack-c', center: { x: 1.3, z: -1.7 }, size: { x: 1.0, z: 5.0 }, height: 2.05 },
      { id: 'rack-d', center: { x: 4.7, z: 1.7 }, size: { x: 1.0, z: 5.0 }, height: 2.05 },
      { id: 'coolant-a', center: { x: -6.8, z: 4.7 }, size: { x: 2.0, z: 1.0 }, height: 1.15 },
      { id: 'coolant-b', center: { x: 6.8, z: -4.7 }, size: { x: 2.0, z: 1.0 }, height: 1.15 },
      { id: 'vault-core', center: { x: 0, z: 0 }, size: { x: 1.6, z: 1.6 }, height: 2.4 },
    ],
    lights: [
      { id: 'server-cyan', position: { x: -5.9, z: -4.8 }, height: 3.1, color: '#55e6ff', intensity: 78, radius: 4.8 },
      { id: 'server-green', position: { x: -0.4, z: 4.6 }, height: 3.2, color: '#8eff81', intensity: 62, radius: 4.3 },
      { id: 'server-red', position: { x: 5.7, z: -2.5 }, height: 3.1, color: '#ff6578', intensity: 66, radius: 4.6 },
      { id: 'vault-exit', position: { x: 5.8, z: 4.2 }, height: 3.0, color: '#a8ffbf', intensity: 70, radius: 3.6 },
    ],
    enemies: [
      {
        id: 'guard-vault-west',
        start: { x: -3.6, z: -5.2 },
        patrol: [
          { x: -3.6, z: -5.2 },
          { x: -3.6, z: 5.2 },
        ],
        speed: 1.05,
        visionRange: 3.35,
        visionAngleDegrees: 58,
        pauseSeconds: 0.22,
      },
      {
        id: 'guard-vault-east',
        start: { x: 3.1, z: 5.2 },
        patrol: [
          { x: 3.1, z: 5.2 },
          { x: 3.1, z: -5.2 },
        ],
        speed: 1.08,
        visionRange: 3.35,
        visionAngleDegrees: 58,
        pauseSeconds: 0.22,
      },
      {
        id: 'guard-vault-core',
        start: { x: -0.2, z: -4.8 },
        patrol: [
          { x: -0.2, z: -4.8 },
          { x: 6.5, z: -4.8 },
          { x: 6.5, z: 4.8 },
          { x: -0.2, z: 4.8 },
        ],
        speed: 0.92,
        visionRange: 3.0,
        visionAngleDegrees: 54,
        pauseSeconds: 0.18,
      },
    ],
    objectives: [
      {
        id: 'vault-keycard',
        type: 'keycard',
        label: 'Vault Keycard',
        position: { x: 0.4, z: 5.6 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'vault-terminal',
        type: 'terminal',
        label: 'Relay Terminal',
        position: { x: 5.9, z: 5.6 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -8, z: -6 },
      { x: -8.4, z: 5.6 },
      { x: -4.0, z: 5.6 },
      { x: 0.4, z: 5.6 },
      { x: 5.9, z: 5.6 },
      { x: 5.8, z: 4.2 },
    ],
  },
  {
    id: 'transit-switchyard',
    name: 'Transit Switchyard',
    briefing: 'Use the outer service lanes and switch boxes to cross a guarded rail bay.',
    parSeconds: 75,
    floorSize: { x: 20, z: 14 },
    start: { x: -5.8, z: -5.8 },
    goal: { x: 8.8, z: -5.8 },
    goalRadius: 0.6,
    obstacles: [
      { id: 'train-west', center: { x: -6.8, z: 0 }, size: { x: 1.1, z: 9.4 }, height: 2.0 },
      { id: 'train-mid-west', center: { x: -3.2, z: -0.2 }, size: { x: 1.1, z: 8.6 }, height: 2.0 },
      { id: 'train-mid-east', center: { x: 1.0, z: 0.1 }, size: { x: 1.1, z: 8.8 }, height: 2.0 },
      { id: 'train-east', center: { x: 4.8, z: 0.9 }, size: { x: 1.1, z: 8.0 }, height: 2.0 },
      { id: 'switch-house', center: { x: -0.2, z: -5.2 }, size: { x: 1.8, z: 1.0 }, height: 1.2 },
      { id: 'tool-locker', center: { x: 6.2, z: -2.7 }, size: { x: 1.2, z: 1.6 }, height: 1.35 },
    ],
    lights: [
      { id: 'rail-west', position: { x: -7.8, z: -4.8 }, height: 3.3, color: '#5ad7ff', intensity: 72, radius: 4.8 },
      { id: 'rail-center', position: { x: -0.8, z: 4.8 }, height: 3.6, color: '#ffd45a', intensity: 64, radius: 4.5 },
      { id: 'rail-east', position: { x: 7.7, z: 1.8 }, height: 3.2, color: '#86ff8a', intensity: 58, radius: 4.1 },
    ],
    enemies: [
      {
        id: 'guard-switch-west',
        start: { x: -8.0, z: -4.8 },
        patrol: [
          { x: -8.0, z: -4.8 },
          { x: -8.0, z: 4.8 },
        ],
        speed: 1.18,
        visionRange: 3.45,
        visionAngleDegrees: 54,
        pauseSeconds: 0.18,
      },
      {
        id: 'guard-switch-center',
        start: { x: -1.7, z: 4.8 },
        patrol: [
          { x: -1.7, z: 4.8 },
          { x: 2.6, z: 4.8 },
          { x: 2.6, z: -4.2 },
          { x: -1.7, z: -4.2 },
        ],
        speed: 1.08,
        visionRange: 3.6,
        visionAngleDegrees: 58,
        pauseSeconds: 0.16,
      },
      {
        id: 'guard-switch-east',
        start: { x: 7.5, z: -4.9 },
        patrol: [
          { x: 7.5, z: -4.9 },
          { x: 7.5, z: 5.2 },
        ],
        speed: 1.1,
        visionRange: 3.5,
        visionAngleDegrees: 56,
        pauseSeconds: 0.2,
      },
    ],
    objectives: [
      {
        id: 'switchyard-keycard',
        type: 'keycard',
        label: 'Rail Keycard',
        position: { x: -4.5, z: -5.8 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'switchyard-relay',
        type: 'terminal',
        label: 'North Relay',
        position: { x: -0.6, z: 5.8 },
        radius: 0.68,
        required: true,
      },
      {
        id: 'switchyard-terminal',
        type: 'terminal',
        label: 'Yard Terminal',
        position: { x: 8.4, z: 1.4 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -5.8, z: -5.8 },
      { x: -4.5, z: -5.8 },
      { x: -2.0, z: -5.8 },
      { x: -2.0, z: 5.8 },
      { x: -0.6, z: 5.8 },
      { x: 8.8, z: 5.8 },
      { x: 8.4, z: 1.4 },
      { x: 8.8, z: -5.8 },
    ],
  },
  {
    id: 'mirror-lab',
    name: 'Mirror Lab',
    briefing: 'Thread the mirrored test lanes while cross patrols watch the gaps.',
    parSeconds: 80,
    floorSize: { x: 20, z: 15 },
    start: { x: -9, z: -6.3 },
    goal: { x: 8.8, z: -6.2 },
    goalRadius: 0.6,
    obstacles: [
      { id: 'mirror-north-a', center: { x: -5.8, z: 3.6 }, size: { x: 5.0, z: 0.8 }, height: 1.7 },
      { id: 'mirror-south-a', center: { x: -5.8, z: -2.7 }, size: { x: 5.0, z: 0.8 }, height: 1.7 },
      { id: 'mirror-north-b', center: { x: 0.2, z: 2.2 }, size: { x: 4.4, z: 0.8 }, height: 1.7 },
      { id: 'mirror-south-b', center: { x: 0.2, z: -4.2 }, size: { x: 4.4, z: 0.8 }, height: 1.7 },
      { id: 'mirror-north-c', center: { x: 5.8, z: 3.2 }, size: { x: 4.5, z: 0.8 }, height: 1.7 },
      { id: 'mirror-south-c', center: { x: 5.8, z: -2.8 }, size: { x: 4.5, z: 0.8 }, height: 1.7 },
      { id: 'control-island', center: { x: 0.0, z: 0 }, size: { x: 1.6, z: 1.6 }, height: 1.25 },
    ],
    lights: [
      { id: 'lab-coolant', position: { x: -7.5, z: 5.6 }, height: 3.3, color: '#55e6ff', intensity: 66, radius: 4.4 },
      { id: 'lab-center', position: { x: 0, z: 0 }, height: 3.7, color: '#b7ffef', intensity: 70, radius: 5.4 },
      { id: 'lab-exit', position: { x: 8.3, z: -5.7 }, height: 3.1, color: '#a8ffbf', intensity: 58, radius: 3.8 },
    ],
    enemies: [
      {
        id: 'guard-lab-west',
        start: { x: -6.8, z: -5.0 },
        patrol: [
          { x: -6.8, z: -5.0 },
          { x: -6.8, z: 5.2 },
        ],
        speed: 1.08,
        visionRange: 3.7,
        visionAngleDegrees: 56,
        pauseSeconds: 0.16,
      },
      {
        id: 'guard-lab-center',
        start: { x: -2.8, z: 0.4 },
        patrol: [
          { x: -2.8, z: 0.4 },
          { x: 3.4, z: 0.4 },
        ],
        speed: 1.25,
        visionRange: 3.5,
        visionAngleDegrees: 60,
        pauseSeconds: 0.12,
      },
      {
        id: 'guard-lab-east',
        start: { x: 6.6, z: 5.0 },
        patrol: [
          { x: 6.6, z: 5.0 },
          { x: 6.6, z: -5.2 },
        ],
        speed: 1.12,
        visionRange: 3.65,
        visionAngleDegrees: 56,
        pauseSeconds: 0.16,
      },
    ],
    objectives: [
      {
        id: 'lab-keycard',
        type: 'keycard',
        label: 'Lab Keycard',
        position: { x: -6.5, z: 5.8 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'lab-terminal-a',
        type: 'terminal',
        label: 'Lens Console',
        position: { x: 0.5, z: 4.8 },
        radius: 0.68,
        required: true,
      },
      {
        id: 'lab-terminal-b',
        type: 'terminal',
        label: 'Prism Console',
        position: { x: 6.8, z: 5.8 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -9, z: -6.3 },
      { x: -9, z: 6.3 },
      { x: -6.5, z: 5.8 },
      { x: 0.5, z: 4.8 },
      { x: 2.8, z: 4.8 },
      { x: 2.8, z: -6.3 },
      { x: 8.8, z: -6.3 },
      { x: 8.8, z: 6.3 },
      { x: 6.8, z: 5.8 },
      { x: 8.8, z: 6.3 },
      { x: 8.8, z: -6.2 },
    ],
  },
  {
    id: 'command-spire',
    name: 'Command Spire',
    briefing: 'Recover the final access chain by circling the spire under overlapping patrols.',
    parSeconds: 95,
    floorSize: { x: 22, z: 16 },
    start: { x: -10, z: -7 },
    goal: { x: 10, z: 7 },
    goalRadius: 0.62,
    obstacles: [
      { id: 'spire-core', center: { x: 0, z: 0 }, size: { x: 2.2, z: 2.2 }, height: 2.6 },
      { id: 'north-wall-west', center: { x: -5.6, z: 2.2 }, size: { x: 1.0, z: 7.2 }, height: 2.1 },
      { id: 'south-wall-west', center: { x: -3.2, z: -2.4 }, size: { x: 1.0, z: 6.8 }, height: 2.1 },
      { id: 'north-wall-east', center: { x: 3.2, z: 2.4 }, size: { x: 1.0, z: 6.8 }, height: 2.1 },
      { id: 'south-wall-east', center: { x: 5.8, z: -2.2 }, size: { x: 1.0, z: 7.2 }, height: 2.1 },
      { id: 'north-console', center: { x: -0.8, z: 5.3 }, size: { x: 2.2, z: 0.8 }, height: 1.1 },
      { id: 'south-console', center: { x: 1.0, z: -5.4 }, size: { x: 2.2, z: 0.8 }, height: 1.1 },
      { id: 'exit-shield', center: { x: 8.0, z: 3.0 }, size: { x: 1.0, z: 3.4 }, height: 1.7 },
    ],
    lights: [
      { id: 'spire-core-light', position: { x: 0, z: 0 }, height: 4.1, color: '#57c7ff', intensity: 120, radius: 6.5 },
      { id: 'spire-north', position: { x: -6.8, z: 6.1 }, height: 3.3, color: '#ffd45a', intensity: 64, radius: 4.1 },
      { id: 'spire-south', position: { x: 6.8, z: -6.1 }, height: 3.3, color: '#ff6578', intensity: 62, radius: 4.1 },
      { id: 'spire-exit', position: { x: 9.6, z: 6.5 }, height: 3.2, color: '#a8ffbf', intensity: 70, radius: 3.8 },
    ],
    enemies: [
      {
        id: 'guard-spire-west',
        start: { x: -8.4, z: 5.8 },
        patrol: [
          { x: -8.4, z: 5.8 },
          { x: -8.4, z: -5.8 },
        ],
        speed: 1.16,
        visionRange: 3.65,
        visionAngleDegrees: 56,
        pauseSeconds: 0.14,
      },
      {
        id: 'guard-spire-inner-a',
        start: { x: -2.0, z: 4.8 },
        patrol: [
          { x: -2.0, z: 4.8 },
          { x: 2.0, z: 4.8 },
          { x: 2.0, z: -4.8 },
          { x: -2.0, z: -4.8 },
        ],
        speed: 1.05,
        visionRange: 3.8,
        visionAngleDegrees: 60,
        pauseSeconds: 0.12,
      },
      {
        id: 'guard-spire-inner-b',
        start: { x: 2.3, z: -4.8 },
        patrol: [
          { x: 2.3, z: -4.8 },
          { x: -2.3, z: -4.8 },
          { x: -2.3, z: 4.8 },
          { x: 2.3, z: 4.8 },
        ],
        speed: 1.02,
        visionRange: 3.7,
        visionAngleDegrees: 58,
        pauseSeconds: 0.12,
      },
      {
        id: 'guard-spire-east',
        start: { x: 8.7, z: -6.2 },
        patrol: [
          { x: 8.7, z: -6.2 },
          { x: 8.7, z: 6.2 },
        ],
        speed: 1.2,
        visionRange: 3.65,
        visionAngleDegrees: 56,
        pauseSeconds: 0.14,
      },
    ],
    objectives: [
      {
        id: 'spire-keycard-west',
        type: 'keycard',
        label: 'West Keycard',
        position: { x: -7.4, z: 6.6 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'spire-terminal-south',
        type: 'terminal',
        label: 'South Console',
        position: { x: -0.5, z: -6.6 },
        radius: 0.68,
        required: true,
      },
      {
        id: 'spire-keycard-east',
        type: 'keycard',
        label: 'East Keycard',
        position: { x: 5.5, z: 6.6 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'spire-terminal-east',
        type: 'terminal',
        label: 'Exit Console',
        position: { x: 9.6, z: -5.8 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -10, z: -7 },
      { x: -10, z: 6.6 },
      { x: -7.4, z: 6.6 },
      { x: -4.6, z: 6.6 },
      { x: -4.6, z: -6.6 },
      { x: -0.5, z: -6.6 },
      { x: 4.4, z: -6.6 },
      { x: 4.4, z: 6.6 },
      { x: 5.5, z: 6.6 },
      { x: 9.6, z: 6.6 },
      { x: 9.6, z: -5.8 },
      { x: 10, z: 7 },
    ],
  },
  {
    id: 'service-gallery',
    name: 'Service Gallery',
    briefing: 'Use the quiet lower service aisle before cutting past a display patrol.',
    parSeconds: 58,
    floorSize: { x: 18, z: 12 },
    start: { x: -8, z: -5 },
    goal: { x: 8, z: 4.8 },
    goalRadius: 0.58,
    obstacles: [
      { id: 'display-west', center: { x: -4.6, z: 0.4 }, size: { x: 1.0, z: 4.6 }, height: 1.35 },
      { id: 'display-mid', center: { x: -0.6, z: -0.8 }, size: { x: 1.0, z: 4.6 }, height: 1.35 },
      { id: 'display-east', center: { x: 3.4, z: 0.6 }, size: { x: 1.0, z: 4.6 }, height: 1.35 },
      { id: 'service-desk', center: { x: 6.1, z: -2.8 }, size: { x: 1.7, z: 1.1 }, height: 1.05 },
      { id: 'gallery-bench', center: { x: -1.7, z: 3.6 }, size: { x: 3.2, z: 0.8 }, height: 0.8 },
    ],
    lights: [
      { id: 'gallery-service', position: { x: -6.8, z: -4.2 }, height: 3.2, color: '#55e6ff', intensity: 58, radius: 4.4 },
      { id: 'gallery-center', position: { x: 0.3, z: 1.5 }, height: 3.8, color: '#d7f6ff', intensity: 54, radius: 5.2 },
      { id: 'gallery-exit', position: { x: 7.8, z: 4.5 }, height: 3.0, color: '#a8ffbf', intensity: 56, radius: 3.5 },
    ],
    enemies: [
      {
        id: 'guard-gallery-floor',
        start: { x: -5.8, z: 1.8 },
        patrol: [
          { x: -5.8, z: 1.8 },
          { x: 5.6, z: 1.8 },
        ],
        speed: 0.98,
        visionRange: 3.1,
        visionAngleDegrees: 54,
        pauseSeconds: 0.3,
      },
      {
        id: 'guard-gallery-service',
        start: { x: 5.6, z: -1.0 },
        patrol: [
          { x: 5.6, z: -1.0 },
          { x: -5.6, z: -1.0 },
        ],
        speed: 0.92,
        visionRange: 2.9,
        visionAngleDegrees: 52,
        pauseSeconds: 0.26,
      },
    ],
    objectives: [
      {
        id: 'gallery-keycard',
        type: 'keycard',
        label: 'Service Keycard',
        position: { x: -3.0, z: -5.0 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'gallery-terminal',
        type: 'terminal',
        label: 'Gallery Console',
        position: { x: 4.8, z: -5.0 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -8, z: -5 },
      { x: -3.0, z: -5.0 },
      { x: 4.8, z: -5.0 },
      { x: 8.1, z: -5.0 },
      { x: 8.1, z: 4.8 },
      { x: 8, z: 4.8 },
    ],
  },
  {
    id: 'cooling-ducts',
    name: 'Cooling Ducts',
    briefing: 'Cross the maintenance ducts by reading long patrol sweeps and using the outer walls.',
    parSeconds: 78,
    floorSize: { x: 22, z: 16 },
    start: { x: -10, z: -7 },
    goal: { x: 9.8, z: 6.8 },
    goalRadius: 0.6,
    obstacles: [
      { id: 'cooling-stack-a', center: { x: -7.2, z: -0.6 }, size: { x: 1.0, z: 8.6 }, height: 2.0 },
      { id: 'cooling-stack-b', center: { x: -3.5, z: 0.8 }, size: { x: 1.0, z: 8.6 }, height: 2.0 },
      { id: 'cooling-stack-c', center: { x: 0.4, z: -0.8 }, size: { x: 1.0, z: 8.8 }, height: 2.0 },
      { id: 'cooling-stack-d', center: { x: 4.3, z: 0.9 }, size: { x: 1.0, z: 8.6 }, height: 2.0 },
      { id: 'pressure-valve', center: { x: 7.6, z: -4.2 }, size: { x: 1.8, z: 1.1 }, height: 1.25 },
      { id: 'fan-housing', center: { x: -8.9, z: 4.8 }, size: { x: 1.4, z: 1.4 }, height: 1.35 },
    ],
    lights: [
      { id: 'duct-cold-west', position: { x: -8.6, z: -5.6 }, height: 3.2, color: '#55e6ff', intensity: 70, radius: 4.7 },
      { id: 'duct-warning', position: { x: -1.2, z: 5.6 }, height: 3.1, color: '#ffb35f', intensity: 58, radius: 4.4 },
      { id: 'duct-cold-east', position: { x: 7.7, z: 2.8 }, height: 3.2, color: '#76d7ff', intensity: 68, radius: 4.6 },
      { id: 'duct-exit', position: { x: 9.4, z: 6.4 }, height: 2.9, color: '#a8ffbf', intensity: 62, radius: 3.5 },
    ],
    enemies: [
      {
        id: 'guard-duct-west',
        start: { x: -9.2, z: -4.6 },
        patrol: [
          { x: -9.2, z: -4.6 },
          { x: -9.2, z: 5.4 },
        ],
        speed: 1.05,
        visionRange: 3.35,
        visionAngleDegrees: 54,
        pauseSeconds: 0.18,
      },
      {
        id: 'guard-duct-mid',
        start: { x: -1.6, z: 5.5 },
        patrol: [
          { x: -1.6, z: 5.5 },
          { x: 2.8, z: 5.5 },
          { x: 2.8, z: -5.4 },
          { x: -1.6, z: -5.4 },
        ],
        speed: 1.04,
        visionRange: 3.25,
        visionAngleDegrees: 56,
        pauseSeconds: 0.16,
      },
      {
        id: 'guard-duct-east',
        start: { x: 7.8, z: 5.3 },
        patrol: [
          { x: 7.8, z: 5.3 },
          { x: 7.8, z: -5.2 },
        ],
        speed: 1.02,
        visionRange: 3.3,
        visionAngleDegrees: 54,
        pauseSeconds: 0.2,
      },
    ],
    objectives: [
      {
        id: 'duct-keycard',
        type: 'keycard',
        label: 'Duct Keycard',
        position: { x: -5.4, z: -7.0 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'duct-terminal-a',
        type: 'terminal',
        label: 'Coolant Relay',
        position: { x: 1.8, z: -7.0 },
        radius: 0.68,
        required: true,
      },
      {
        id: 'duct-terminal-b',
        type: 'terminal',
        label: 'Fan Console',
        position: { x: 9.5, z: -1.8 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -10, z: -7 },
      { x: -5.4, z: -7.0 },
      { x: 1.8, z: -7.0 },
      { x: 9.5, z: -7.0 },
      { x: 9.5, z: -1.8 },
      { x: 9.8, z: 6.8 },
    ],
  },
  {
    id: 'datacore-maze',
    name: 'Datacore Maze',
    briefing: 'Work through offset data walls while guards cover the center lanes.',
    parSeconds: 94,
    floorSize: { x: 24, z: 16 },
    start: { x: -11, z: -6.8 },
    goal: { x: 11, z: 6.8 },
    goalRadius: 0.62,
    obstacles: [
      { id: 'maze-wall-a', center: { x: -8.0, z: -1.8 }, size: { x: 1.0, z: 8.0 }, height: 2.1 },
      { id: 'maze-wall-b', center: { x: -4.2, z: 1.8 }, size: { x: 1.0, z: 8.0 }, height: 2.1 },
      { id: 'maze-wall-c', center: { x: -0.4, z: -1.8 }, size: { x: 1.0, z: 8.0 }, height: 2.1 },
      { id: 'maze-wall-d', center: { x: 3.4, z: 1.8 }, size: { x: 1.0, z: 8.0 }, height: 2.1 },
      { id: 'maze-wall-e', center: { x: 7.2, z: -1.4 }, size: { x: 1.0, z: 7.2 }, height: 2.1 },
      { id: 'core-node', center: { x: 1.4, z: 0 }, size: { x: 1.6, z: 1.6 }, height: 2.45 },
      { id: 'data-desk', center: { x: -10.0, z: 3.9 }, size: { x: 1.6, z: 1.0 }, height: 1.1 },
      { id: 'exit-baffle', center: { x: 9.3, z: 3.0 }, size: { x: 1.0, z: 2.7 }, height: 1.6 },
    ],
    lights: [
      { id: 'datacore-west', position: { x: -9.2, z: -5.8 }, height: 3.1, color: '#5ad7ff', intensity: 68, radius: 4.7 },
      { id: 'datacore-node', position: { x: 1.4, z: 0 }, height: 4.0, color: '#57c7ff', intensity: 110, radius: 6.0 },
      { id: 'datacore-warning', position: { x: 6.3, z: -5.4 }, height: 3.2, color: '#ff6578', intensity: 60, radius: 4.2 },
      { id: 'datacore-exit', position: { x: 10.6, z: 6.4 }, height: 3.0, color: '#a8ffbf', intensity: 64, radius: 3.7 },
    ],
    enemies: [
      {
        id: 'guard-datacore-west',
        start: { x: -10.4, z: 5.0 },
        patrol: [
          { x: -10.4, z: 5.0 },
          { x: -10.4, z: -5.2 },
        ],
        speed: 1.12,
        visionRange: 3.5,
        visionAngleDegrees: 54,
        pauseSeconds: 0.14,
      },
      {
        id: 'guard-datacore-lane-a',
        start: { x: -6.1, z: -5.2 },
        patrol: [
          { x: -6.1, z: -5.2 },
          { x: -6.1, z: 5.2 },
        ],
        speed: 1.08,
        visionRange: 3.45,
        visionAngleDegrees: 54,
        pauseSeconds: 0.14,
      },
      {
        id: 'guard-datacore-lane-b',
        start: { x: 1.5, z: 5.2 },
        patrol: [
          { x: 1.5, z: 5.2 },
          { x: 1.5, z: -5.2 },
        ],
        speed: 1.1,
        visionRange: 3.45,
        visionAngleDegrees: 54,
        pauseSeconds: 0.14,
      },
      {
        id: 'guard-datacore-east',
        start: { x: 9.2, z: -5.0 },
        patrol: [
          { x: 9.2, z: -5.0 },
          { x: 9.2, z: 5.0 },
        ],
        speed: 1.14,
        visionRange: 3.5,
        visionAngleDegrees: 54,
        pauseSeconds: 0.14,
      },
    ],
    objectives: [
      {
        id: 'datacore-keycard-west',
        type: 'keycard',
        label: 'West Access',
        position: { x: -9.8, z: -6.8 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'datacore-terminal',
        type: 'terminal',
        label: 'Core Console',
        position: { x: -2.1, z: 6.8 },
        radius: 0.68,
        required: true,
      },
      {
        id: 'datacore-keycard-east',
        type: 'keycard',
        label: 'East Access',
        position: { x: 8.1, z: -6.8 },
        radius: 0.62,
        required: true,
      },
    ],
    validationRoute: [
      { x: -11, z: -6.8 },
      { x: -9.8, z: -6.8 },
      { x: -6.3, z: -6.8 },
      { x: -6.3, z: 6.8 },
      { x: -2.1, z: 6.8 },
      { x: 5.3, z: 6.8 },
      { x: 5.3, z: -6.8 },
      { x: 8.1, z: -6.8 },
      { x: 11, z: -6.8 },
      { x: 11, z: 6.8 },
    ],
  },
  {
    id: 'blackout-crown',
    name: 'Blackout Crown',
    briefing: 'Complete the final crown circuit while layered sentries sweep each perimeter.',
    parSeconds: 118,
    floorSize: { x: 24, z: 18 },
    start: { x: -11, z: -8 },
    goal: { x: 11, z: 8 },
    goalRadius: 0.64,
    obstacles: [
      { id: 'crown-core', center: { x: 0, z: 0 }, size: { x: 2.4, z: 2.4 }, height: 2.7 },
      { id: 'crown-wall-west-a', center: { x: -7.6, z: -2.2 }, size: { x: 1.0, z: 8.4 }, height: 2.15 },
      { id: 'crown-wall-west-b', center: { x: -4.4, z: 2.4 }, size: { x: 1.0, z: 8.0 }, height: 2.15 },
      { id: 'crown-wall-mid-a', center: { x: -1.2, z: -2.2 }, size: { x: 1.0, z: 8.2 }, height: 2.15 },
      { id: 'crown-wall-mid-b', center: { x: 2.2, z: 2.4 }, size: { x: 1.0, z: 8.0 }, height: 2.15 },
      { id: 'crown-wall-east-a', center: { x: 5.4, z: -2.2 }, size: { x: 1.0, z: 8.2 }, height: 2.15 },
      { id: 'crown-wall-east-b', center: { x: 8.3, z: 2.2 }, size: { x: 1.0, z: 7.4 }, height: 2.15 },
      { id: 'north-console-bank', center: { x: -1.0, z: 6.1 }, size: { x: 3.2, z: 0.8 }, height: 1.1 },
      { id: 'south-console-bank', center: { x: 1.1, z: -6.1 }, size: { x: 3.2, z: 0.8 }, height: 1.1 },
      { id: 'exit-shield-crown', center: { x: 9.4, z: 5.2 }, size: { x: 1.0, z: 3.2 }, height: 1.7 },
    ],
    lights: [
      { id: 'crown-core-light', position: { x: 0, z: 0 }, height: 4.2, color: '#57c7ff', intensity: 118, radius: 6.6 },
      { id: 'crown-west-light', position: { x: -9.6, z: 6.8 }, height: 3.2, color: '#ffd45a', intensity: 64, radius: 4.4 },
      { id: 'crown-south-light', position: { x: 3.8, z: -7.0 }, height: 3.2, color: '#ff6578', intensity: 62, radius: 4.3 },
      { id: 'crown-east-light', position: { x: 9.5, z: -3.4 }, height: 3.2, color: '#55e6ff', intensity: 64, radius: 4.2 },
      { id: 'crown-exit-light', position: { x: 10.5, z: 7.6 }, height: 3.0, color: '#a8ffbf', intensity: 72, radius: 3.8 },
    ],
    enemies: [
      {
        id: 'guard-crown-west',
        start: { x: -10.0, z: 6.3 },
        patrol: [
          { x: -10.0, z: 6.3 },
          { x: -10.0, z: -6.3 },
        ],
        speed: 1.18,
        visionRange: 3.55,
        visionAngleDegrees: 54,
        pauseSeconds: 0.12,
      },
      {
        id: 'guard-crown-lane-a',
        start: { x: -5.8, z: -6.4 },
        patrol: [
          { x: -5.8, z: -6.4 },
          { x: -5.8, z: 6.4 },
        ],
        speed: 1.1,
        visionRange: 3.5,
        visionAngleDegrees: 54,
        pauseSeconds: 0.12,
      },
      {
        id: 'guard-crown-inner',
        start: { x: -2.2, z: 5.2 },
        patrol: [
          { x: -2.2, z: 5.2 },
          { x: 2.6, z: 5.2 },
          { x: 2.6, z: -5.2 },
          { x: -2.2, z: -5.2 },
        ],
        speed: 1.08,
        visionRange: 3.65,
        visionAngleDegrees: 58,
        pauseSeconds: 0.1,
      },
      {
        id: 'guard-crown-lane-b',
        start: { x: 6.8, z: 6.4 },
        patrol: [
          { x: 6.8, z: 6.4 },
          { x: 6.8, z: -6.4 },
        ],
        speed: 1.12,
        visionRange: 3.5,
        visionAngleDegrees: 54,
        pauseSeconds: 0.12,
      },
      {
        id: 'guard-crown-east',
        start: { x: 10.0, z: -6.4 },
        patrol: [
          { x: 10.0, z: -6.4 },
          { x: 10.0, z: 6.4 },
        ],
        speed: 1.2,
        visionRange: 3.55,
        visionAngleDegrees: 54,
        pauseSeconds: 0.12,
      },
    ],
    objectives: [
      {
        id: 'crown-keycard-west',
        type: 'keycard',
        label: 'West Crown',
        position: { x: -9.6, z: -8.0 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'crown-terminal-north',
        type: 'terminal',
        label: 'North Crown',
        position: { x: -3.0, z: 8.0 },
        radius: 0.68,
        required: true,
      },
      {
        id: 'crown-keycard-east',
        type: 'keycard',
        label: 'East Crown',
        position: { x: 7.2, z: -8.0 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'crown-terminal-exit',
        type: 'terminal',
        label: 'Exit Crown',
        position: { x: 10.2, z: -3.2 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -11, z: -8 },
      { x: -9.6, z: -8.0 },
      { x: -6.6, z: -8.0 },
      { x: -6.6, z: 8.0 },
      { x: -3.0, z: 8.0 },
      { x: 4.5, z: 8.0 },
      { x: 4.5, z: -8.0 },
      { x: 7.2, z: -8.0 },
      { x: 10.2, z: -8.0 },
      { x: 10.2, z: -3.2 },
      { x: 11, z: -3.2 },
      { x: 11, z: 8 },
    ],
  },
];

export function getLevel(index: number): LevelDefinition {
  return levels[((index % levels.length) + levels.length) % levels.length];
}
