import type { LevelDefinition } from './types';

const sharedCrates = [
  { id: 'crate-a', center: { x: -3.1, z: -0.7 }, size: { x: 1.2, z: 2.3 }, height: 1.35 },
  { id: 'crate-b', center: { x: 1.4, z: 1.1 }, size: { x: 1.1, z: 3.4 }, height: 1.55 },
  { id: 'crate-c', center: { x: 4.1, z: -1.8 }, size: { x: 1.6, z: 1.1 }, height: 1.1 },
] as const;

export const levels: readonly LevelDefinition[] = [
  {
    id: 'dock-blackout',
    name: 'Dock Blackout',
    briefing: 'Slip through a half-lit cargo bay and reach the service hatch.',
    parSeconds: 35,
    floorSize: { x: 12, z: 9 },
    start: { x: -5, z: 3.4 },
    goal: { x: 5, z: -3.2 },
    goalRadius: 0.55,
    obstacles: sharedCrates,
    lights: [
      { id: 'lamp-north', position: { x: -2.5, z: -3.2 }, height: 3.4, color: '#6ab7ff', intensity: 95, radius: 5.6 },
      { id: 'lamp-exit', position: { x: 4.6, z: -2.8 }, height: 2.9, color: '#a7ffcb', intensity: 55, radius: 3.2 },
    ],
    enemies: [
      {
        id: 'guard-dock',
        start: { x: -0.2, z: -2.5 },
        patrol: [
          { x: -0.2, z: -2.5 },
          { x: 3.2, z: -2.5 },
          { x: 3.2, z: 2.6 },
          { x: -0.2, z: 2.6 },
        ],
        speed: 1.08,
        visionRange: 3.2,
        visionAngleDegrees: 64,
        pauseSeconds: 0.3,
      },
    ],
    objectives: [
      {
        id: 'dock-keycard',
        type: 'keycard',
        label: 'Gate Keycard',
        position: { x: -1.0, z: -1.2 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'dock-terminal',
        type: 'terminal',
        label: 'Exit Terminal',
        position: { x: 2.4, z: -3.4 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -5, z: 3.4 },
      { x: -4.8, z: -3.8 },
      { x: -1.6, z: -3.8 },
      { x: -1.0, z: -1.2 },
      { x: 2.4, z: -3.4 },
      { x: 5, z: -3.2 },
    ],
  },
  {
    id: 'archive-lanes',
    name: 'Archive Lanes',
    briefing: 'Cross the records room while patrols sweep the narrow aisles.',
    parSeconds: 55,
    floorSize: { x: 14, z: 10 },
    start: { x: -6, z: 4 },
    goal: { x: 6.1, z: -4 },
    goalRadius: 0.55,
    obstacles: [
      { id: 'shelf-a', center: { x: -3.5, z: 0 }, size: { x: 0.9, z: 7.2 }, height: 1.8 },
      { id: 'shelf-b', center: { x: 0.2, z: 0.8 }, size: { x: 0.9, z: 7.2 }, height: 1.8 },
      { id: 'shelf-c', center: { x: 3.8, z: -0.7 }, size: { x: 0.9, z: 7.2 }, height: 1.8 },
      { id: 'desk', center: { x: -5.3, z: -2.6 }, size: { x: 1.7, z: 1.3 }, height: 1.0 },
    ],
    lights: [
      { id: 'lamp-aisle-a', position: { x: -5.3, z: 1.8 }, height: 3.3, color: '#ffd58a', intensity: 62, radius: 4.1 },
      { id: 'lamp-aisle-b', position: { x: 1.9, z: -1.8 }, height: 3.2, color: '#76d7ff', intensity: 72, radius: 4.8 },
      { id: 'lamp-goal', position: { x: 5.9, z: -3.5 }, height: 2.7, color: '#7dff9b', intensity: 48, radius: 3.0 },
    ],
    enemies: [
      {
        id: 'guard-archive-a',
        start: { x: -1.8, z: 3.5 },
        patrol: [
          { x: -1.8, z: 3.5 },
          { x: -1.8, z: -3.5 },
        ],
        speed: 0.95,
        visionRange: 3.3,
        visionAngleDegrees: 58,
        pauseSeconds: 0.45,
      },
      {
        id: 'guard-archive-b',
        start: { x: 2.1, z: -3.7 },
        patrol: [
          { x: 2.1, z: -3.7 },
          { x: 2.1, z: 3.6 },
        ],
        speed: 1.05,
        visionRange: 3.1,
        visionAngleDegrees: 58,
        pauseSeconds: 0.25,
      },
    ],
    objectives: [
      {
        id: 'archive-keycard',
        type: 'keycard',
        label: 'Archive Keycard',
        position: { x: -2.1, z: -4.1 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'archive-terminal',
        type: 'terminal',
        label: 'Records Terminal',
        position: { x: 2.6, z: -4.6 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -6, z: 4 },
      { x: -6.5, z: 4.7 },
      { x: -6.5, z: -3.9 },
      { x: -2.1, z: -4.1 },
      { x: -1.5, z: 4.7 },
      { x: 1.7, z: 4.7 },
      { x: 2.6, z: -4.6 },
      { x: 4.6, z: -4.6 },
      { x: 6.1, z: -4 },
    ],
  },
  {
    id: 'reactor-core',
    name: 'Reactor Core',
    briefing: 'Use cover and timing to cross the reactor floor before lockdown.',
    parSeconds: 60,
    floorSize: { x: 16, z: 11 },
    start: { x: -7, z: 4.4 },
    goal: { x: 7.1, z: -4.4 },
    goalRadius: 0.58,
    obstacles: [
      { id: 'reactor', center: { x: 0, z: 0 }, size: { x: 2.4, z: 2.4 }, height: 2.35 },
      { id: 'console-a', center: { x: -4.7, z: -2.8 }, size: { x: 2.2, z: 1.0 }, height: 1.1 },
      { id: 'console-b', center: { x: 4.7, z: 2.7 }, size: { x: 2.2, z: 1.0 }, height: 1.1 },
      { id: 'pillar-a', center: { x: -2.9, z: 3.1 }, size: { x: 1.1, z: 1.1 }, height: 2.4 },
      { id: 'pillar-b', center: { x: 2.9, z: -3.1 }, size: { x: 1.1, z: 1.1 }, height: 2.4 },
    ],
    lights: [
      { id: 'core-blue', position: { x: 0, z: 0 }, height: 3.1, color: '#57c7ff', intensity: 135, radius: 6.8 },
      { id: 'warning-left', position: { x: -5.6, z: -3.8 }, height: 2.6, color: '#ff5f68', intensity: 52, radius: 3.1 },
      { id: 'warning-right', position: { x: 5.8, z: 3.8 }, height: 2.6, color: '#ffb35f', intensity: 52, radius: 3.1 },
    ],
    enemies: [
      {
        id: 'guard-core-a',
        start: { x: -5.6, z: 0.1 },
        patrol: [
          { x: -5.6, z: 0.1 },
          { x: -1.9, z: -3.6 },
          { x: 1.8, z: -3.6 },
        ],
        speed: 1.15,
        visionRange: 3.6,
        visionAngleDegrees: 62,
        pauseSeconds: 0.2,
      },
      {
        id: 'guard-core-b',
        start: { x: 5.6, z: -0.1 },
        patrol: [
          { x: 5.6, z: -0.1 },
          { x: 1.9, z: 3.6 },
          { x: -1.8, z: 3.6 },
        ],
        speed: 1.12,
        visionRange: 3.6,
        visionAngleDegrees: 62,
        pauseSeconds: 0.2,
      },
    ],
    objectives: [
      {
        id: 'reactor-terminal',
        type: 'terminal',
        label: 'Core Terminal',
        position: { x: -2.5, z: 1.6 },
        radius: 0.68,
        required: true,
      },
      {
        id: 'reactor-keycard',
        type: 'keycard',
        label: 'Reactor Keycard',
        position: { x: 6.7, z: 4.2 },
        radius: 0.62,
        required: true,
      },
    ],
    validationRoute: [
      { x: -7, z: 4.4 },
      { x: -6.8, z: -4.4 },
      { x: -3.2, z: -4.5 },
      { x: -2.5, z: 1.6 },
      { x: 2.3, z: 4.5 },
      { x: 6.7, z: 4.2 },
      { x: 7.1, z: -4.4 },
    ],
  },
  {
    id: 'neon-atrium',
    name: 'Neon Atrium',
    briefing: 'Thread the perimeter of a glass-lit lobby while patrols cross the center.',
    parSeconds: 50,
    floorSize: { x: 18, z: 12 },
    start: { x: -7.2, z: 0.5 },
    goal: { x: 8, z: -5 },
    goalRadius: 0.58,
    obstacles: [
      { id: 'kiosk-west', center: { x: -5.7, z: 1.4 }, size: { x: 1.4, z: 2.2 }, height: 1.25 },
      { id: 'kiosk-east', center: { x: 5.8, z: -1.4 }, size: { x: 1.4, z: 2.2 }, height: 1.25 },
      { id: 'planter-north', center: { x: -1.8, z: -3.2 }, size: { x: 3.6, z: 0.9 }, height: 0.9 },
      { id: 'planter-south', center: { x: 2.0, z: 3.1 }, size: { x: 3.6, z: 0.9 }, height: 0.9 },
      { id: 'glass-a', center: { x: -2.4, z: 0.1 }, size: { x: 0.7, z: 4.2 }, height: 1.9 },
      { id: 'glass-b', center: { x: 2.8, z: -0.1 }, size: { x: 0.7, z: 4.2 }, height: 1.9 },
      { id: 'ticket-desk', center: { x: 0, z: 4.6 }, size: { x: 2.9, z: 0.8 }, height: 1.0 },
    ],
    lights: [
      { id: 'neon-blue', position: { x: -6.5, z: -3.8 }, height: 3.4, color: '#48b8ff', intensity: 82, radius: 5.2 },
      { id: 'neon-magenta', position: { x: 4.9, z: 3.8 }, height: 3.4, color: '#ff58b8', intensity: 76, radius: 5.0 },
      { id: 'atrium-center', position: { x: 0, z: 0 }, height: 4.2, color: '#b7ffef', intensity: 54, radius: 4.6 },
      { id: 'atrium-exit', position: { x: 7.7, z: -4.7 }, height: 2.8, color: '#86ff8a', intensity: 48, radius: 3.2 },
    ],
    enemies: [
      {
        id: 'guard-atrium-cross',
        start: { x: -4.5, z: -1.2 },
        patrol: [
          { x: -4.5, z: -1.2 },
          { x: 4.5, z: -1.2 },
          { x: 4.5, z: 1.2 },
          { x: -4.5, z: 1.2 },
        ],
        speed: 1.22,
        visionRange: 3.7,
        visionAngleDegrees: 60,
        pauseSeconds: 0.18,
      },
      {
        id: 'guard-atrium-ring',
        start: { x: -6.8, z: -4.2 },
        patrol: [
          { x: -6.8, z: -4.2 },
          { x: 6.8, z: -4.2 },
          { x: 6.8, z: 4.2 },
          { x: -6.8, z: 4.2 },
        ],
        speed: 1.0,
        visionRange: 3.4,
        visionAngleDegrees: 56,
        pauseSeconds: 0.25,
      },
    ],
    objectives: [
      {
        id: 'atrium-keycard',
        type: 'keycard',
        label: 'Atrium Keycard',
        position: { x: -3.8, z: -5.2 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'atrium-terminal',
        type: 'terminal',
        label: 'Lobby Terminal',
        position: { x: 3.8, z: -5.2 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -7.2, z: 0.5 },
      { x: -8.3, z: -5.2 },
      { x: -3.8, z: -5.2 },
      { x: 3.8, z: -5.2 },
      { x: 8, z: -5 },
    ],
  },
  {
    id: 'signal-vault',
    name: 'Signal Vault',
    briefing: 'Break through a hardened relay room by weaving between server stacks.',
    parSeconds: 65,
    floorSize: { x: 18, z: 14 },
    start: { x: -8, z: -6 },
    goal: { x: 5.8, z: 4.2 },
    goalRadius: 0.6,
    obstacles: [
      { id: 'rack-a', center: { x: -5.4, z: -1.7 }, size: { x: 1.0, z: 5.0 }, height: 2.05 },
      { id: 'rack-b', center: { x: -2.1, z: 1.7 }, size: { x: 1.0, z: 5.0 }, height: 2.05 },
      { id: 'rack-c', center: { x: 1.3, z: -1.7 }, size: { x: 1.0, z: 5.0 }, height: 2.05 },
      { id: 'rack-d', center: { x: 4.7, z: 1.7 }, size: { x: 1.0, z: 5.0 }, height: 2.05 },
      { id: 'coolant-a', center: { x: -6.8, z: 4.7 }, size: { x: 2.0, z: 1.0 }, height: 1.15 },
      { id: 'coolant-b', center: { x: 6.8, z: -4.7 }, size: { x: 2.0, z: 1.0 }, height: 1.15 },
      { id: 'vault-core', center: { x: 0, z: 0 }, size: { x: 1.6, z: 1.6 }, height: 2.4 },
    ],
    lights: [
      { id: 'server-cyan', position: { x: -5.9, z: -4.8 }, height: 3.1, color: '#55e6ff', intensity: 78, radius: 4.8 },
      { id: 'server-green', position: { x: -0.4, z: 4.6 }, height: 3.2, color: '#8eff81', intensity: 62, radius: 4.3 },
      { id: 'server-red', position: { x: 5.7, z: -2.5 }, height: 3.1, color: '#ff6578', intensity: 66, radius: 4.6 },
      { id: 'vault-exit', position: { x: 5.8, z: 4.2 }, height: 3.0, color: '#a8ffbf', intensity: 70, radius: 3.6 },
    ],
    enemies: [
      {
        id: 'guard-vault-west',
        start: { x: -3.6, z: -5.2 },
        patrol: [
          { x: -3.6, z: -5.2 },
          { x: -3.6, z: 5.2 },
        ],
        speed: 1.05,
        visionRange: 3.35,
        visionAngleDegrees: 58,
        pauseSeconds: 0.22,
      },
      {
        id: 'guard-vault-east',
        start: { x: 3.1, z: 5.2 },
        patrol: [
          { x: 3.1, z: 5.2 },
          { x: 3.1, z: -5.2 },
        ],
        speed: 1.08,
        visionRange: 3.35,
        visionAngleDegrees: 58,
        pauseSeconds: 0.22,
      },
      {
        id: 'guard-vault-core',
        start: { x: -0.2, z: -4.8 },
        patrol: [
          { x: -0.2, z: -4.8 },
          { x: 6.5, z: -4.8 },
          { x: 6.5, z: 4.8 },
          { x: -0.2, z: 4.8 },
        ],
        speed: 0.92,
        visionRange: 3.0,
        visionAngleDegrees: 54,
        pauseSeconds: 0.18,
      },
    ],
    objectives: [
      {
        id: 'vault-keycard',
        type: 'keycard',
        label: 'Vault Keycard',
        position: { x: 0.4, z: 5.6 },
        radius: 0.62,
        required: true,
      },
      {
        id: 'vault-terminal',
        type: 'terminal',
        label: 'Relay Terminal',
        position: { x: 5.9, z: 5.6 },
        radius: 0.68,
        required: true,
      },
    ],
    validationRoute: [
      { x: -8, z: -6 },
      { x: -8.4, z: 5.6 },
      { x: -4.0, z: 5.6 },
      { x: 0.4, z: 5.6 },
      { x: 5.9, z: 5.6 },
      { x: 5.8, z: 4.2 },
    ],
  },
];

export function getLevel(index: number): LevelDefinition {
  return levels[((index % levels.length) + levels.length) % levels.length];
}
